name: Kingspeech
favicon: null
layout_spectrum: 0.11125810304656625
typography_spectrum: 0.16416910896077752
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6180337977129966
  lightness: 0.2482754613738507
  saturation: 0.6364046554081142
  rhythmicContrast: 0.975632558343932
purpose: []
